### ISSUE TITLE
Print progress while downloading artifacts

### ISSUE THREAD

**Issue by gmierz** [marco-c/firefox-code-coverage#20]
When codecoverage.py is run, there is no output for a very long time and this gives the impression that the program is frozen. There should be some output at each step of the process that describes what the program is currently doing. I think that going for a few minutes is fine without output, but the user should be notified that it could take some time if there is a particular point that has to run for a long time without output.

**Comment by marco-c** [comment]
I forgot that there is already a message here while running grcov: https://github.com/marco-c/firefox-code-coverage/blob/master/codecoverage.py#L141.

So I suppose the slowness you experienced must due to something else.

**Comment by gmierz** [comment]
I think it might be the downloading that is taking some time.
