### ISSUE TITLE
Remove common prefix automatically

### ISSUE THREAD

**Issue by rhcu** [marco-c/firefox-code-coverage#46]
From `genhtml` docs prefix can be removed automatically:

>  --prefix prefix
Remove prefix from all directory names.
Because lists containing long filenames are difficult to read, there is a mechanism implemented that will automatically try to shorten all directory names on the overview page beginning with a common prefix. By default, this is done using an algorithm that tries to find the prefix which, when applied, will minimize the resulting sum of characters of all directory names.
Use this option to specify the prefix to be removed by yourself. 

Without specifying this option here: https://github.com/marco-c/firefox-code-coverage/blob/3c70be1de846dde18bc5e8d51320e67ec6601e4f/firefox_code_coverage/codecoverage.py#L220 the list with files doesn't contain the path to the repo in filenames. Relevant to: https://github.com/mozilla/coverage-crawler/issues/125

They will look like this: https://rhcu.github.io/coverage-crawler-reports/

**Comment by marco-c** [comment]
I wonder why it doesn't work with the prefix we set, maybe src_dir is a relative path? If it is, maybe we can use os.path.abspath(src_dir)?

**Comment by marco-c** [comment]
Anyway, it sounds like the best option is to rely on the automatic algorithm like you said :)

**Comment by rhcu** [comment]
More likely, this is because we pass a relative path that doesn't work for strip string function.
